---
certbot_email: "{{ lookup('env', 'CERTBOT_EMAIL') | default('', true) }}"

### should not touch in general ####################################################################

ssh_user: "{{ lookup('env', 'SSH_USER') | default('deploy', true) }}"
# only to set if inventory_hostname is not a resolvable DNS name
domain: "{{ lookup('env', 'EXPLICIT_DOMAIN') | default(inventory_hostname, true) }}"
ssh_key_dir: "{{ lookup('env', 'SSH_KEY_DIR') | default(lookup('env', 'HOME') + '/.ssh', true) }}"
ssh_key_path: "{{ ssh_key_dir }}/{{ ssh_user }}_{{ (ansible_host | default(inventory_hostname)) | regex_replace('[^A-Za-z0-9.-]', '_') }}"
ct2html_cgi_path: "{{ lookup('env', 'CT2HTML_CGI_PATH') | default('/opt/ct2html/ct2html-cgi', true) }}"

####################################################################################################