name: Deploy Nginx

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dawidd6/action-ansible-playbook@v9
        with:
          playbook: nginx.yml
          directory: install
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory inventory.ini
